### PR TITLE
season and year column

### PR DESCRIPTION
**Pull request by YiranZhao**
added year and season

### CODE REVIEW

**Comment by youngseojeong** [comment]
Can you make edits in the README to include seasons? otherwise the code looks good!

**Comment by YiranZhao** [comment]
[invert.genera.season.zip](https://github.com/eeb313-2019/the-motion-of-the-ocean/files/3895049/invert.genera.season.zip)

**Comment by YiranZhao** [comment]
the website can't upload csv file for some reason so I uploaded it in a zip file

**Comment by youngseojeong** [comment]
looks good!

**Comment by nikol-d97** [comment]
looks great!

**Pull request merged**
